apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-2"
  labels:
    app.kubernetes.io/instance: regclient
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: regclient-12.0.2
  name: keystorejob-regclient
  namespace: regclient
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: regclient
        app.kubernetes.io/managed-by: Helm
        helm.sh/chart: regclient-12.0.2
        job-name: keystorejob-regclient
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - env:
        - name: NAMESPACE
          value: regclient
        image: mosipdev/regclient-keystore:release-1.2.0.x
        imagePullPolicy: Always
        name: openssl-container
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/mosip/certs
          name: certs-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: regclient-foo
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: certs-volume
        
        
===========================================================================================================================

Mallesh shared for reg-client. for 1202 deployment
